const ResumeActionTypes = {
  SET_MAIN_COLOR: 'SET_MAIN_COLOR',
  SET_MAIN_FONT: 'SET_MAIN_FONT',
  ADD_NEW_SKILL: 'ADD_NEW_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',
  TOGGLE_SECTION: 'TOGGLE_SECTION',
  SET_PREVIEW_IMAGE_URL: 'SET_PREVIEW_IMAGE_URL',
  SET_PROFILE_PICTURE: 'SET_PROFILE_PICTURE',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  SET_OVERFLOW_ALERT: 'SET_OVERFLOW_ALERT',
};

export default ResumeActionTypes;
